### ISSUE TITLE
Server crash once and boss blocks

### ISSUE THREAD

**Issue by KamiSami** [TeamChocoQuest/ChocolateQuestRepoured#118]
**Describe the bug**
When i reach to boss room i find a boss block that i assume is supposed to spawn in boss but it does not do it and remains there.

**To Reproduce**
(The crash steps is unknown, but..)
1. For the boss, just find any structure i believe with boss in it
2.  Find the boss block
3. And.. It's there...
4. And... It's still there...

**Expected behavior**
To see boss spawn in? And no crash occassionally about of this mod i think?

**Screenshots**
https://imgur.com/VgDYj2x

**Versions**
Chocolate Quest Repoured: ChocolateQuestRepoured-1.12.2-1.1.0B.jar
Forge: forge-14.23.5.2847
Minecraft: Minecraft Version: 1.12.2

**Other**
Crash report: https://pastebin.com/kgQht8ND Server Crash report
Log file: Idk, server or client log? Tries paste server log in pastebin but too big to paste it
Singleplayer/Multiplayer: Multiplayer
Other mods (that are necessary to produce the bug): I... Have no idea.
Other mods (that are also installed): Too many to write them all i guess, but if needed i will get the list of them. Let me know if needed.

**Comment by LordEpos** [comment]
This is a known thing, some dungeons don't have bosses yet, so it's just there as a placeholder. As we add more bosses, they'll get filled in.

Crash should be fixed in today's version unless we did something wrong.

Not gonna close this, so that others reporting it hopefully notice this one, but suffice to say that we're working on it by adding more bosses.

**Comment by DerToaster98** [comment]
Should be fixed with next alpha release
