### ISSUE TITLE
Crash with Streams mod

### ISSUE THREAD

**Issue by tappaja666** [TeamChocoQuest/ChocolateQuestRepoured#176]
**Describe the bug**
Crash with the Streams mod when a streams replaces chocolate quest spawner?

**To Reproduce**
Hard to reproduce since structure and it's rotation can be different on the same seed but the seed is -8277021698281969431 and location is -426 -385 (requires other mods to get same generation)
.
.
.

**Versions**
Chocolate Quest Repoured: Alpha 20
Forge: 14.23.5.2847
Minecraft: 1.12.2

**Other**
Crash report: https://paste.dimdev.org/uqohitodof.mccrash
Log file: https://puu.sh/FzI5y/c783a0e3be.log
Singleplayer/Multiplayer: Singleplayer
Other mods (that are necessary to produce the bug): Farseek, Streams
Other mods (that are also installed): https://puu.sh/FzImL/ae554fec65.png

**Comment by DerToaster98** [comment]
This wont be worked on as it is too complex to reproduce and actually verify that the bug is gone. 

Please try to narrow it down to how exactly reproduce this with <10 mods

Also this is more an issue with streams than with CQR cause it seems that streams deletes the spawner tile entity which isnt good practice to do so.

Also why would "streams replaces chocolate quest spawner" ? There is no reason for it to do so. CQR generates it structures after terrain generation

**Comment by Meldexun** [comment]
Should be fixed.
