### ISSUE TITLE
The structures are not generating.

### ISSUE THREAD

**Issue by Mateusz7073** [TeamChocoQuest/ChocolateQuestRepoured#180]
**Describe the bug**
I was making a modpack with TLauncher and I have downloaded this awesome mod, basing on my expirence with better dungeons from the past. But something is wrong, the structures are not generating at all. I have even tried to install it without any other mod and it still wasnt working. I have no idea what can cause this... (Llibary was downloaded automatically with it)

**To Reproduce**
I dont know what to tell, I have downloaded it from Tl mods, the Tlauncher mods downloader.

**Expected behavior**
I dont know

**Screenshots**
*EMPTY  SPACE*

**Versions**
Chocolate Quest Repoured: Alpha 20
Forge: forge 14.23.5.2847
Minecraft: 1.12.2

**Other**
Crash report: none
Log file: nope
Singleplayer/Multiplayer: single
Other mods (that are necessary to produce the bug): none
Other mods (that are also installed): none

**Comment by Mateusz7073** [comment]
( Missclick :P ) btw I know that I have it installed because I have mobs and items from it.

**Comment by Meldexun** [comment]
So first of all your version of CQR is outdated. (No support for old versions)
Also you should only download mods from official sites. (CQR can be downloaded on curseforge or on our discord server)
I'm pretty sure you just haven't looked enough for dungeons. With the default config there will be no dungeons in a 25 chunk radius around the spawn point and because the dungeon seperation is 20 chunks you will have to walk around 40 chunks on one axis to find a dungeon. Even then it is not guaranteed that a dungeon will spawn. Also you can lower the dungeon seperation (in config/cqrepoured.cfg) or increase the spawn chance for each dungeon (in config/CQR/dungeons).
If you still can't find any dungeon then we need at least a log file.

**Comment by DerToaster98** [comment]
This is not a bug. The dungeons ARE rare. You just need to search for a while. 
If you want them to be more common, turn down the "dungeonSeparation" in the config (the distance that has to be between two dungeons measured in chunks) and turn up the "chance" for each dungeon config inside the "dungeons" folder which is located in the "CQR" folder

**Comment by Mateusz7073** [comment]
You are right, they are indeed rare. I also havent noticed that spawning structures on superflat worlds was turned off. Thanks for the answers
