### ISSUE TITLE
Invisibilty

### ISSUE THREAD

**Issue by KingOres** [TeamChocoQuest/ChocolateQuestRepoured#189]
CQR mobs can see when invisible.

**Comment by DerToaster98** [comment]
Since you emit particles (on the floor when walking and from the potion)  when invisible they *can* theoretically see you, also your gear (armor + hand items) is visible. This also is the case for vanilla mos as far as i know, i don't see a need to fix (actually this is the wrong word, we don't care about entities being invisible code wise) this, but it maybe will be implemented.
