### ISSUE TITLE
No Dungeons Generating

### ISSUE THREAD

**Issue by AdriPlaysz** [TeamChocoQuest/ChocolateQuestRepoured#226]
I play with just this mod version 27.8
and llbrary-1.7.19-1.12.2

and i cannot find any dungeons in my world :(.

**Comment by DerToaster98** [comment]
This is not a bug. 

I hope you do know that dungeons can only spawn in newly generated chunks and that forge is required to run the whole mod.

Otherwise the structures ARE RARE and don't spawn in a certain radius around the spawn. I suggest you to consult our wiki (not the fandom one), it is linked on the curseforge page.
