### ISSUE TITLE
pls make it compatible to biomes o plenty

### ISSUE THREAD

**Issue by mkowskyyy** [TeamChocoQuest/ChocolateQuestRepoured#259]
it is not i know thats why i am writing this pls make it like original mod

**Comment by DerToaster98** [comment]
it is compatible with biomes o plenty.

And stop spamming the issue tracker!

**Comment by DerToaster98** [comment]
If this really is a bug: CQR works fine with mods like OTG ( even confirmed by it's developer), the issue clearly is on BoP's side, report it to them, that also is the case for other structure mods (https://github.com/Glitchfiend/BiomesOPlenty/issues/1812)

So please: Report this to BoP or manually add all their biome id's to cqr's configs. Cause the issue seems to occur from BoP apparently not assigning biome types to their biomes (CQR uses those AND the biome ID's, biome types are some sort of classification of biomes (e.g. Forest or River)).

**Comment by Meldexun** [comment]
No, CQR and BoP work fine together. The mentioned BoP issue happens in MC 1.16.5.
Maybe you messed up the configs or you didn't delete the old configs when updating. So you can try deleting the `minecraft/config/CQR` folder and the `minecraft/config/cqrepoured.cfg` file.
