### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Kasia1403** [TeamChocoQuest/ChocolateQuestRepoured#294]
[crash-2021-11-12_14.51.48-client.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/7574663/crash-2021-11-12_14.51.48-client.txt)

[crash-2021-11-12_14.50.33-server.txt](https://github.com/TeamChocoQuest/ChocolateQuestRepoured/files/7574666/crash-2021-11-12_14.50.33-server.txt)

**Comment by DerToaster98** [comment]
You don't provide us any information on what the problem is, what causes it, what you did to the configs, etc.

And now you expect us to magically know the problem in a installation with a lot of additional possible causes?

No, we won't help you. You don't even tell us what is wrong and don't provide us any information necessary for us to solve the issue in the first place.

And spamming our issue tracker doesn't help as well.

Is it really so difficult to use common sense to **read** the issue template that actually explains what to do to report bugs?

If you open another issue following the same schema you will be blocked from this repository

**Comment by Kasia1403** [comment]
I will try with DEFAULT settings, but if it will not help then I will be writing here again ! And I added exclamation mark because I'm very angry. And I tried to find configs that about which You wrote, but I don't know in which structures this Nether Dragon spawns.And I will tell You why I have problems - this is because I'm disabled.

**Comment by DerToaster98** [comment]
Closed because of refusing to provide necessary information.

In addition it makes no sense arguing with an individual that rather keeps spamming instead of providing the information asked for in the template. In addition arguing with upset people makes no sense.

**Comment by DerToaster98** [comment]
Once you've calmed down: Please follow these steps:
- Update the mod (newest version is 2.6.1B) and geckolib (required is 3.0.11)
- Test if your issue still persists
- If yes, uninstall all other mods except geckolib and cqrepoured
- If the problem still exists, open a new issue and fill out the template this time. Without the informations in the template we can't help you

**Comment by DerToaster98** [comment]
On the nether dragon: I think i told you that he doesn't appear anywhere currently, so it can't possibly be the cause for your problems

**Comment by DerToaster98** [comment]
Also to let you know: I took a look at your crash-report here and the one you posted on biomes'o'plenty.

The netherdragon is not the cause for your problem. The problem most likely is biomes'o'plenty and not us.
Please report your problems to them and not us.

**Comment by Kasia1403** [comment]
I'm affraid that Biomes O'Plenty developers / authors will not want to help because their issue tracker says only about 1.17. And what if they will not help ?

**Comment by DerToaster98** [comment]
Then do what i mentioned earlier. That is following these steps:
1) Update cqr and geckolib. CQR to version 2.6.1B and geckolib to 3.0.11
2) Check if the problem still exists
3) If yes, check if the problem persists with just cqr and geckolib (in a new world)
4) If it still persists with just cqr, then please create a new issue and fill out the template. That way we have the information we need and can actually attempt to fix the problem.

If the problem does not occur with just CQR then we won't likely do something. What you can do is testing what mod creates the problem by slowly adding the other mods one-by-one and checking if the problem persists.

If the problem is indeed a bop problem and they won't do something about it then it is like it is. If i were you i would just uninstall bop.
